MENU_WINDOW_CONFIGS:
  "GEOMETRY": "1024x768"
  "RESIZABLE": False
  "BACKGROUND_COLOR_DEFAULT": 'white'
  "FOREGROUND_COLOR_DEFAULT": 'black'
  "FONT_DEFAULT": 'Arial 12'
  "FONT_BOLD": 'Arial 12 bold'
  "FONT_ITALIC": 'Arial 12 italic'
  "FONT_UNDERLINE": 'Arial 12 underline'
  "FONT_OVERSTRIKE": 'Arial 12 overstrike'
  "FONT_SIZE_DEFAULT": 12
  "FONT_SIZE_SMALL": 10
  "FONT_SIZE_MEDIUM": 12
  "FONT_SIZE_LARGE": 14

ALARM_WINDOW_CONFIGS:
  "WINDOW_WIDTH": 280
  "WINDOW_HEIGHT": 200
  "RESIZABLE": False
  "BACKGROUND_COLOR_DEFAULT": 'white'
  "FOREGROUND_COLOR_DEFAULT": 'black'
  "FONT_DEFAULT": 'Arial 12'

